package Forms;

import Graphs.DataReader;
import Graphs.GraphFinder;
import Graphs.SCCFinder;
import java.io.File;
import java.io.FileNotFoundException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import org.jgraph.graph.DefaultEdge;
import org.jgrapht.DirectedGraph;
import org.jgrapht.graph.DefaultDirectedGraph;

/**
 *
 * @author Kanakarakis Ivan
 */
public class MainWindow extends javax.swing.JFrame {
	final JFileChooser fc = new JFileChooser();
	File file;

	/** Creates new form MainWindow */
	public MainWindow() {
		//this.setIconImage(new javax.swing.ImageIcon(getClass().getResource(AppDefs.MAIN_ICON)).getImage());
		this.setLocationRelativeTo(null);
		initComponents();
		startBut.setEnabled(false);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanel1 = new javax.swing.JPanel();
                fileTextField = new javax.swing.JTextField();
                openBut = new javax.swing.JButton();
                startBut = new javax.swing.JButton();
                sccNumTextField = new javax.swing.JTextField();
                sccNumLbl = new javax.swing.JLabel();
                sccSizeLbl = new javax.swing.JLabel();
                jScrollPane2 = new javax.swing.JScrollPane();
                sccSizeTextArea = new javax.swing.JTextArea();
                diameterLbl = new javax.swing.JLabel();
                diameterTextField = new javax.swing.JTextField();
                jScrollPane1 = new javax.swing.JScrollPane();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setTitle("JGraphs");

                fileTextField.setEditable(false);

                openBut.setText("Open FIle");
                openBut.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                openButActionPerformed(evt);
                        }
                });

                startBut.setText("Start");
                startBut.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                startButActionPerformed(evt);
                        }
                });

                sccNumTextField.setEditable(false);

                sccNumLbl.setText("SSC# :");

                sccSizeLbl.setText("SSC's size:");

                sccSizeTextArea.setColumns(20);
                sccSizeTextArea.setEditable(false);
                sccSizeTextArea.setRows(5);
                jScrollPane2.setViewportView(sccSizeTextArea);

                diameterLbl.setText("Diameter:");

                diameterTextField.setEditable(false);

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(diameterLbl)
                                                        .addComponent(sccNumLbl))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(diameterTextField)
                                                        .addComponent(sccNumTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(startBut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(openBut, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE))
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(18, 18, 18)
                                                                .addComponent(fileTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                                .addGap(77, 77, 77)
                                                                .addComponent(sccSizeLbl)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                );
                jPanel1Layout.setVerticalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(openBut)
                                                        .addComponent(fileTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(sccSizeLbl)
                                                        .addComponent(startBut))
                                                .addGap(7, 7, 7)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(sccNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(sccNumLbl))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(diameterLbl)
                                                        .addComponent(diameterTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(14, 14, 14))))
                );

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 657, Short.MAX_VALUE)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                                .addGap(29, 29, 29)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

    private void openButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openButActionPerformed
	    if (evt.getSource() == openBut) {
		    fc.setDragEnabled(true);
		    int retVal = fc.showOpenDialog(jPanel1);
		    if (retVal == JFileChooser.APPROVE_OPTION) {
			    file = fc.getSelectedFile();
			    fileTextField.setText(file.getName());
			    startBut.setEnabled(true);
		    }
	    }
    }//GEN-LAST:event_openButActionPerformed

    private void startButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButActionPerformed
	    DirectedGraph<String, DefaultEdge> directedGraph = new DefaultDirectedGraph<String, DefaultEdge>(DefaultEdge.class);
	    try {
		    DataReader dr = new DataReader(file);
		    if (dr.readFile(directedGraph)) {
			    SCCFinder scc = new SCCFinder(directedGraph);
			    int[] sccSizes = scc.getSCCSizePerSubgraph();
			    sccNumTextField.setText(String.valueOf(sccSizes.length));
			    for (int sccNum = 0; sccNum < sccSizes.length; sccNum++)
				    sccSizeTextArea.append(String.format("%d SCC size: %d\n", sccNum + 1, sccSizes[sccNum]));
			    diameterTextField.setText(String.valueOf((new GraphFinder(directedGraph)).getGreatestDiameter()));
		    } else {
			    throw new FileNotFoundException();
		    }
	    } catch (FileNotFoundException fnfe) {
		    JOptionPane.showMessageDialog(this, "Unable to read data\nPlease choose another file",
						  "Error Reading File!", JOptionPane.ERROR_MESSAGE);
		    fnfe.printStackTrace();
	    }
    }//GEN-LAST:event_startButActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				try {   // Set System L&F
					UIManager.setLookAndFeel(
						UIManager.getSystemLookAndFeelClassName());
				} catch (UnsupportedLookAndFeelException e) {
					// handle exception
				} catch (ClassNotFoundException e) {
					// handle exception
				} catch (InstantiationException e) {
					// handle exception
				} catch (IllegalAccessException e) {
					// handle exception
				}
				new MainWindow().setVisible(true);
			}

		});
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JLabel diameterLbl;
        private javax.swing.JTextField diameterTextField;
        private javax.swing.JTextField fileTextField;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JScrollPane jScrollPane2;
        private javax.swing.JButton openBut;
        private javax.swing.JLabel sccNumLbl;
        private javax.swing.JTextField sccNumTextField;
        private javax.swing.JLabel sccSizeLbl;
        private javax.swing.JTextArea sccSizeTextArea;
        private javax.swing.JButton startBut;
        // End of variables declaration//GEN-END:variables
}
